// Code generated by ent, DO NOT EDIT.

package internshipbatch

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/omkar273/codegeeky/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldContainsFold(FieldID, id))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldUpdatedBy, v))
}

// InternshipID applies equality check predicate on the "internship_id" field. It's identical to InternshipIDEQ.
func InternshipID(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldInternshipID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldDescription, v))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldStartDate, v))
}

// EndDate applies equality check predicate on the "end_date" field. It's identical to EndDateEQ.
func EndDate(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldEndDate, v))
}

// BatchStatus applies equality check predicate on the "batch_status" field. It's identical to BatchStatusEQ.
func BatchStatus(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldBatchStatus, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNotNull(FieldMetadata))
}

// InternshipIDEQ applies the EQ predicate on the "internship_id" field.
func InternshipIDEQ(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldInternshipID, v))
}

// InternshipIDNEQ applies the NEQ predicate on the "internship_id" field.
func InternshipIDNEQ(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNEQ(FieldInternshipID, v))
}

// InternshipIDIn applies the In predicate on the "internship_id" field.
func InternshipIDIn(vs ...string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldIn(FieldInternshipID, vs...))
}

// InternshipIDNotIn applies the NotIn predicate on the "internship_id" field.
func InternshipIDNotIn(vs ...string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNotIn(FieldInternshipID, vs...))
}

// InternshipIDGT applies the GT predicate on the "internship_id" field.
func InternshipIDGT(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGT(FieldInternshipID, v))
}

// InternshipIDGTE applies the GTE predicate on the "internship_id" field.
func InternshipIDGTE(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGTE(FieldInternshipID, v))
}

// InternshipIDLT applies the LT predicate on the "internship_id" field.
func InternshipIDLT(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLT(FieldInternshipID, v))
}

// InternshipIDLTE applies the LTE predicate on the "internship_id" field.
func InternshipIDLTE(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLTE(FieldInternshipID, v))
}

// InternshipIDContains applies the Contains predicate on the "internship_id" field.
func InternshipIDContains(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldContains(FieldInternshipID, v))
}

// InternshipIDHasPrefix applies the HasPrefix predicate on the "internship_id" field.
func InternshipIDHasPrefix(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldHasPrefix(FieldInternshipID, v))
}

// InternshipIDHasSuffix applies the HasSuffix predicate on the "internship_id" field.
func InternshipIDHasSuffix(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldHasSuffix(FieldInternshipID, v))
}

// InternshipIDEqualFold applies the EqualFold predicate on the "internship_id" field.
func InternshipIDEqualFold(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEqualFold(FieldInternshipID, v))
}

// InternshipIDContainsFold applies the ContainsFold predicate on the "internship_id" field.
func InternshipIDContainsFold(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldContainsFold(FieldInternshipID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldContainsFold(FieldDescription, v))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLTE(FieldStartDate, v))
}

// StartDateIsNil applies the IsNil predicate on the "start_date" field.
func StartDateIsNil() predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldIsNull(FieldStartDate))
}

// StartDateNotNil applies the NotNil predicate on the "start_date" field.
func StartDateNotNil() predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNotNull(FieldStartDate))
}

// EndDateEQ applies the EQ predicate on the "end_date" field.
func EndDateEQ(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldEndDate, v))
}

// EndDateNEQ applies the NEQ predicate on the "end_date" field.
func EndDateNEQ(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNEQ(FieldEndDate, v))
}

// EndDateIn applies the In predicate on the "end_date" field.
func EndDateIn(vs ...time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldIn(FieldEndDate, vs...))
}

// EndDateNotIn applies the NotIn predicate on the "end_date" field.
func EndDateNotIn(vs ...time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNotIn(FieldEndDate, vs...))
}

// EndDateGT applies the GT predicate on the "end_date" field.
func EndDateGT(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGT(FieldEndDate, v))
}

// EndDateGTE applies the GTE predicate on the "end_date" field.
func EndDateGTE(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGTE(FieldEndDate, v))
}

// EndDateLT applies the LT predicate on the "end_date" field.
func EndDateLT(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLT(FieldEndDate, v))
}

// EndDateLTE applies the LTE predicate on the "end_date" field.
func EndDateLTE(v time.Time) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLTE(FieldEndDate, v))
}

// EndDateIsNil applies the IsNil predicate on the "end_date" field.
func EndDateIsNil() predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldIsNull(FieldEndDate))
}

// EndDateNotNil applies the NotNil predicate on the "end_date" field.
func EndDateNotNil() predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNotNull(FieldEndDate))
}

// BatchStatusEQ applies the EQ predicate on the "batch_status" field.
func BatchStatusEQ(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEQ(FieldBatchStatus, v))
}

// BatchStatusNEQ applies the NEQ predicate on the "batch_status" field.
func BatchStatusNEQ(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNEQ(FieldBatchStatus, v))
}

// BatchStatusIn applies the In predicate on the "batch_status" field.
func BatchStatusIn(vs ...string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldIn(FieldBatchStatus, vs...))
}

// BatchStatusNotIn applies the NotIn predicate on the "batch_status" field.
func BatchStatusNotIn(vs ...string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldNotIn(FieldBatchStatus, vs...))
}

// BatchStatusGT applies the GT predicate on the "batch_status" field.
func BatchStatusGT(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGT(FieldBatchStatus, v))
}

// BatchStatusGTE applies the GTE predicate on the "batch_status" field.
func BatchStatusGTE(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldGTE(FieldBatchStatus, v))
}

// BatchStatusLT applies the LT predicate on the "batch_status" field.
func BatchStatusLT(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLT(FieldBatchStatus, v))
}

// BatchStatusLTE applies the LTE predicate on the "batch_status" field.
func BatchStatusLTE(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldLTE(FieldBatchStatus, v))
}

// BatchStatusContains applies the Contains predicate on the "batch_status" field.
func BatchStatusContains(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldContains(FieldBatchStatus, v))
}

// BatchStatusHasPrefix applies the HasPrefix predicate on the "batch_status" field.
func BatchStatusHasPrefix(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldHasPrefix(FieldBatchStatus, v))
}

// BatchStatusHasSuffix applies the HasSuffix predicate on the "batch_status" field.
func BatchStatusHasSuffix(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldHasSuffix(FieldBatchStatus, v))
}

// BatchStatusEqualFold applies the EqualFold predicate on the "batch_status" field.
func BatchStatusEqualFold(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldEqualFold(FieldBatchStatus, v))
}

// BatchStatusContainsFold applies the ContainsFold predicate on the "batch_status" field.
func BatchStatusContainsFold(v string) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.FieldContainsFold(FieldBatchStatus, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InternshipBatch) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InternshipBatch) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InternshipBatch) predicate.InternshipBatch {
	return predicate.InternshipBatch(sql.NotPredicates(p))
}
