basePath: /api/v1
definitions:
  dto.SignupRequest:
    properties:
      access_token:
        description: access token
        type: string
      email:
        description: basic info
        type: string
      full_name:
        type: string
      phone:
        type: string
      role:
        allOf:
        - $ref: '#/definitions/types.UserRole'
        description: role
    required:
    - access_token
    - email
    - full_name
    - role
    type: object
  dto.SignupResponse:
    properties:
      access_token:
        type: string
      id:
        type: string
    type: object
  types.UserRole:
    enum:
    - STUDENT
    - INSTRUCTOR
    - ADMIN
    type: string
    x-enum-varnames:
    - UserRoleStudent
    - UserRoleInstructor
    - UserRoleAdmin
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
  description: API for CodeGeeky
  termsOfService: http://example.com/terms/
  title: CodeGeeky API
  version: "1.0"
paths:
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Signup
      parameters:
      - description: Signup request
        in: body
        name: signupRequest
        required: true
        schema:
          $ref: '#/definitions/dto.SignupRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.SignupResponse'
      summary: Signup
      tags:
      - Auth
securityDefinitions:
  Authorization:
    description: Enter the token with the `Bearer ` prefix, e.g. `Bearer <token>`.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
