// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/omkar273/codegeeky/ent/internshipbatch"
	"github.com/omkar273/codegeeky/ent/predicate"
)

// InternshipBatchDelete is the builder for deleting a InternshipBatch entity.
type InternshipBatchDelete struct {
	config
	hooks    []Hook
	mutation *InternshipBatchMutation
}

// Where appends a list predicates to the InternshipBatchDelete builder.
func (ibd *InternshipBatchDelete) Where(ps ...predicate.InternshipBatch) *InternshipBatchDelete {
	ibd.mutation.Where(ps...)
	return ibd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ibd *InternshipBatchDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ibd.sqlExec, ibd.mutation, ibd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ibd *InternshipBatchDelete) ExecX(ctx context.Context) int {
	n, err := ibd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ibd *InternshipBatchDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(internshipbatch.Table, sqlgraph.NewFieldSpec(internshipbatch.FieldID, field.TypeString))
	if ps := ibd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ibd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ibd.mutation.done = true
	return affected, err
}

// InternshipBatchDeleteOne is the builder for deleting a single InternshipBatch entity.
type InternshipBatchDeleteOne struct {
	ibd *InternshipBatchDelete
}

// Where appends a list predicates to the InternshipBatchDelete builder.
func (ibdo *InternshipBatchDeleteOne) Where(ps ...predicate.InternshipBatch) *InternshipBatchDeleteOne {
	ibdo.ibd.mutation.Where(ps...)
	return ibdo
}

// Exec executes the deletion query.
func (ibdo *InternshipBatchDeleteOne) Exec(ctx context.Context) error {
	n, err := ibdo.ibd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{internshipbatch.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ibdo *InternshipBatchDeleteOne) ExecX(ctx context.Context) {
	if err := ibdo.Exec(ctx); err != nil {
		panic(err)
	}
}
