// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/omkar273/codegeeky/ent/internshipenrollment"
	"github.com/omkar273/codegeeky/ent/predicate"
)

// InternshipEnrollmentQuery is the builder for querying InternshipEnrollment entities.
type InternshipEnrollmentQuery struct {
	config
	ctx        *QueryContext
	order      []internshipenrollment.OrderOption
	inters     []Interceptor
	predicates []predicate.InternshipEnrollment
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the InternshipEnrollmentQuery builder.
func (ieq *InternshipEnrollmentQuery) Where(ps ...predicate.InternshipEnrollment) *InternshipEnrollmentQuery {
	ieq.predicates = append(ieq.predicates, ps...)
	return ieq
}

// Limit the number of records to be returned by this query.
func (ieq *InternshipEnrollmentQuery) Limit(limit int) *InternshipEnrollmentQuery {
	ieq.ctx.Limit = &limit
	return ieq
}

// Offset to start from.
func (ieq *InternshipEnrollmentQuery) Offset(offset int) *InternshipEnrollmentQuery {
	ieq.ctx.Offset = &offset
	return ieq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ieq *InternshipEnrollmentQuery) Unique(unique bool) *InternshipEnrollmentQuery {
	ieq.ctx.Unique = &unique
	return ieq
}

// Order specifies how the records should be ordered.
func (ieq *InternshipEnrollmentQuery) Order(o ...internshipenrollment.OrderOption) *InternshipEnrollmentQuery {
	ieq.order = append(ieq.order, o...)
	return ieq
}

// First returns the first InternshipEnrollment entity from the query.
// Returns a *NotFoundError when no InternshipEnrollment was found.
func (ieq *InternshipEnrollmentQuery) First(ctx context.Context) (*InternshipEnrollment, error) {
	nodes, err := ieq.Limit(1).All(setContextOp(ctx, ieq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{internshipenrollment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ieq *InternshipEnrollmentQuery) FirstX(ctx context.Context) *InternshipEnrollment {
	node, err := ieq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first InternshipEnrollment ID from the query.
// Returns a *NotFoundError when no InternshipEnrollment ID was found.
func (ieq *InternshipEnrollmentQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ieq.Limit(1).IDs(setContextOp(ctx, ieq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{internshipenrollment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ieq *InternshipEnrollmentQuery) FirstIDX(ctx context.Context) string {
	id, err := ieq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single InternshipEnrollment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one InternshipEnrollment entity is found.
// Returns a *NotFoundError when no InternshipEnrollment entities are found.
func (ieq *InternshipEnrollmentQuery) Only(ctx context.Context) (*InternshipEnrollment, error) {
	nodes, err := ieq.Limit(2).All(setContextOp(ctx, ieq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{internshipenrollment.Label}
	default:
		return nil, &NotSingularError{internshipenrollment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ieq *InternshipEnrollmentQuery) OnlyX(ctx context.Context) *InternshipEnrollment {
	node, err := ieq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only InternshipEnrollment ID in the query.
// Returns a *NotSingularError when more than one InternshipEnrollment ID is found.
// Returns a *NotFoundError when no entities are found.
func (ieq *InternshipEnrollmentQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ieq.Limit(2).IDs(setContextOp(ctx, ieq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{internshipenrollment.Label}
	default:
		err = &NotSingularError{internshipenrollment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ieq *InternshipEnrollmentQuery) OnlyIDX(ctx context.Context) string {
	id, err := ieq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of InternshipEnrollments.
func (ieq *InternshipEnrollmentQuery) All(ctx context.Context) ([]*InternshipEnrollment, error) {
	ctx = setContextOp(ctx, ieq.ctx, ent.OpQueryAll)
	if err := ieq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*InternshipEnrollment, *InternshipEnrollmentQuery]()
	return withInterceptors[[]*InternshipEnrollment](ctx, ieq, qr, ieq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ieq *InternshipEnrollmentQuery) AllX(ctx context.Context) []*InternshipEnrollment {
	nodes, err := ieq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of InternshipEnrollment IDs.
func (ieq *InternshipEnrollmentQuery) IDs(ctx context.Context) (ids []string, err error) {
	if ieq.ctx.Unique == nil && ieq.path != nil {
		ieq.Unique(true)
	}
	ctx = setContextOp(ctx, ieq.ctx, ent.OpQueryIDs)
	if err = ieq.Select(internshipenrollment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ieq *InternshipEnrollmentQuery) IDsX(ctx context.Context) []string {
	ids, err := ieq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ieq *InternshipEnrollmentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ieq.ctx, ent.OpQueryCount)
	if err := ieq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ieq, querierCount[*InternshipEnrollmentQuery](), ieq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ieq *InternshipEnrollmentQuery) CountX(ctx context.Context) int {
	count, err := ieq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ieq *InternshipEnrollmentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ieq.ctx, ent.OpQueryExist)
	switch _, err := ieq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ieq *InternshipEnrollmentQuery) ExistX(ctx context.Context) bool {
	exist, err := ieq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the InternshipEnrollmentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ieq *InternshipEnrollmentQuery) Clone() *InternshipEnrollmentQuery {
	if ieq == nil {
		return nil
	}
	return &InternshipEnrollmentQuery{
		config:     ieq.config,
		ctx:        ieq.ctx.Clone(),
		order:      append([]internshipenrollment.OrderOption{}, ieq.order...),
		inters:     append([]Interceptor{}, ieq.inters...),
		predicates: append([]predicate.InternshipEnrollment{}, ieq.predicates...),
		// clone intermediate query.
		sql:  ieq.sql.Clone(),
		path: ieq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Status string `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.InternshipEnrollment.Query().
//		GroupBy(internshipenrollment.FieldStatus).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ieq *InternshipEnrollmentQuery) GroupBy(field string, fields ...string) *InternshipEnrollmentGroupBy {
	ieq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &InternshipEnrollmentGroupBy{build: ieq}
	grbuild.flds = &ieq.ctx.Fields
	grbuild.label = internshipenrollment.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status string `json:"status,omitempty"`
//	}
//
//	client.InternshipEnrollment.Query().
//		Select(internshipenrollment.FieldStatus).
//		Scan(ctx, &v)
func (ieq *InternshipEnrollmentQuery) Select(fields ...string) *InternshipEnrollmentSelect {
	ieq.ctx.Fields = append(ieq.ctx.Fields, fields...)
	sbuild := &InternshipEnrollmentSelect{InternshipEnrollmentQuery: ieq}
	sbuild.label = internshipenrollment.Label
	sbuild.flds, sbuild.scan = &ieq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a InternshipEnrollmentSelect configured with the given aggregations.
func (ieq *InternshipEnrollmentQuery) Aggregate(fns ...AggregateFunc) *InternshipEnrollmentSelect {
	return ieq.Select().Aggregate(fns...)
}

func (ieq *InternshipEnrollmentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ieq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ieq); err != nil {
				return err
			}
		}
	}
	for _, f := range ieq.ctx.Fields {
		if !internshipenrollment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ieq.path != nil {
		prev, err := ieq.path(ctx)
		if err != nil {
			return err
		}
		ieq.sql = prev
	}
	return nil
}

func (ieq *InternshipEnrollmentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*InternshipEnrollment, error) {
	var (
		nodes = []*InternshipEnrollment{}
		_spec = ieq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*InternshipEnrollment).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &InternshipEnrollment{config: ieq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ieq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ieq *InternshipEnrollmentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ieq.querySpec()
	_spec.Node.Columns = ieq.ctx.Fields
	if len(ieq.ctx.Fields) > 0 {
		_spec.Unique = ieq.ctx.Unique != nil && *ieq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ieq.driver, _spec)
}

func (ieq *InternshipEnrollmentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(internshipenrollment.Table, internshipenrollment.Columns, sqlgraph.NewFieldSpec(internshipenrollment.FieldID, field.TypeString))
	_spec.From = ieq.sql
	if unique := ieq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ieq.path != nil {
		_spec.Unique = true
	}
	if fields := ieq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, internshipenrollment.FieldID)
		for i := range fields {
			if fields[i] != internshipenrollment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ieq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ieq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ieq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ieq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ieq *InternshipEnrollmentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ieq.driver.Dialect())
	t1 := builder.Table(internshipenrollment.Table)
	columns := ieq.ctx.Fields
	if len(columns) == 0 {
		columns = internshipenrollment.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ieq.sql != nil {
		selector = ieq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ieq.ctx.Unique != nil && *ieq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ieq.predicates {
		p(selector)
	}
	for _, p := range ieq.order {
		p(selector)
	}
	if offset := ieq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ieq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// InternshipEnrollmentGroupBy is the group-by builder for InternshipEnrollment entities.
type InternshipEnrollmentGroupBy struct {
	selector
	build *InternshipEnrollmentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (iegb *InternshipEnrollmentGroupBy) Aggregate(fns ...AggregateFunc) *InternshipEnrollmentGroupBy {
	iegb.fns = append(iegb.fns, fns...)
	return iegb
}

// Scan applies the selector query and scans the result into the given value.
func (iegb *InternshipEnrollmentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, iegb.build.ctx, ent.OpQueryGroupBy)
	if err := iegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InternshipEnrollmentQuery, *InternshipEnrollmentGroupBy](ctx, iegb.build, iegb, iegb.build.inters, v)
}

func (iegb *InternshipEnrollmentGroupBy) sqlScan(ctx context.Context, root *InternshipEnrollmentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(iegb.fns))
	for _, fn := range iegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*iegb.flds)+len(iegb.fns))
		for _, f := range *iegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*iegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := iegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// InternshipEnrollmentSelect is the builder for selecting fields of InternshipEnrollment entities.
type InternshipEnrollmentSelect struct {
	*InternshipEnrollmentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ies *InternshipEnrollmentSelect) Aggregate(fns ...AggregateFunc) *InternshipEnrollmentSelect {
	ies.fns = append(ies.fns, fns...)
	return ies
}

// Scan applies the selector query and scans the result into the given value.
func (ies *InternshipEnrollmentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ies.ctx, ent.OpQuerySelect)
	if err := ies.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InternshipEnrollmentQuery, *InternshipEnrollmentSelect](ctx, ies.InternshipEnrollmentQuery, ies, ies.inters, v)
}

func (ies *InternshipEnrollmentSelect) sqlScan(ctx context.Context, root *InternshipEnrollmentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ies.fns))
	for _, fn := range ies.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ies.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ies.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
