# server
server:
  env: "local"
  address: ":8080"

# logging
logging:
  level: "info"

# postgres
postgres:
  host: "localhost"
  port: 5432
  user: "your_username"
  password: "your_password"
  dbname: "your_database"
  sslmode: "disable"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime_minutes: 60
  auto_migrate: true

# supabase
supabase:
  url: "https://dummy.supabase.co"
  key: "dummy_key"
  jwt_secret: "dummy_jwt_secret"
  service_key: "dummy_service_key"
  dev_api_key: "dev_api_key_for_development_only"

# secrets
secrets:
  encryption_key: "dummy_encryption_key"

# cloudinary
cloudinary:
  api_key: "1234567890"
  api_secret: "1234567890"
  cloud_name: "dummy_cloud_name"
  api_base_url: "https://api.cloudinary.com"

cache:
  enabled: true

razorpay:
  api_key: "rzp_test_1234567890"
  api_secret: "1234567890"

webhook:
  enabled: false
  pubsub: "memory"
  topic: "webhooks"
  max_retries: 3
  initial_interval: 1s
  max_interval: 10s
  multiplier: 2.0
  max_elapsed_time: 2m
  memory:
    enabled: true
    max_messages: 1000
    max_message_size: 1024
    max_message_ttl: 60000
    max_message_batch_size: 100
    max_message_batch_timeout: 1000
  kafka:
    enabled: false
    brokers:
      - "localhost:9092"
    topic: "codegeeky-webhook"
    group_id: "codegeeky-webhook-group"
    auto_offset_reset: "earliest"
    enable_auto_commit: true
    session_timeout: 30000
